# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	libsysstat
PORTVERSION=	0.3.1
CATEGORIES=	sysutils
MASTER_SITES=	LXQT/${PORTNAME}

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Library used to query system info and statistics

USES=	cmake:outsource lxqt pkgconfig tar:xz
USE_QT5=	core

.include <bsd.port.mk>
