# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-l10n
PORTVERSION=	0.13.0
CATEGORIES=	x11

MAINTAINER=	jesper@schmitz.computer
COMMENT=	Translations of LXQt components

LICENSE=	LGPL21+

RUN_DEPENDS=	liblxqt-l10n>=0.13:devel/liblxqt-l10n \
		lximageqt-l10n>=0.13:graphics/lximageqt-l10n \
		libfmqt-l10n>=0.13:x11/libfmqt-l10n \
		pcmanfmqt-l10n>=0.13:x11-fm/pcmanfmqt-l10n \
		lxqt-config-l10n>=0.13:sysutils/lxqt-config-l10n \
		lxqt-policykit-l10n>=0.13:sysutils/lxqt-policykit-l10n \
		lxqt-about-l10n>=0.13:x11/lxqt-about-l10n \
		lxqt-globalkeys-l10n>=0.13:x11/lxqt-globalkeys-l10n \
		lxqt-runner-l10n>=0.13:x11/lxqt-runner-l10n \
		pavucontrolqt-l10n>=0.13:audio/pavucontrolqt-l10n \
		obconfqt-l10n>=0.13:x11-wm/obconfqt-l10n \
		lxqt-panel-l10n>=0.13:x11-wm/lxqt-panel-l10n \
		lxqt-session-l10n>=0.13:x11-wm/lxqt-session-l10n \
		lxqt-admin-l10n>=0.13:sysutils/lxqt-admin-l10n \
		lxqt-notificationd-l10n>=0.13:deskutils/lxqt-notificationd-l10n

USES=		metaport qt:5

.include <bsd.port.mk>
