# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-l10n
PORTVERSION=	0.11.0
CATEGORIES=	x11
MASTER_SITES=	LXQT

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Translations of LXQt components

LICENSE=	LGPL21+

RUN_DEPENDS=	lxqt-liblxqt-l10n>=0.11:devel/lxqt-liblxqt-l10n \
	lxqt-notificationd-l10n>=0.11:deskutils/lxqt-notificationd-l10n \
	lxqt-lximage-l10n>=0.11:graphics/lxqt-lximage-l10n \
	lxqt-openssh-l10n>=0.11:security/lxqt-openssh-l10n \
	lxqt-sudo-l10n>=0.11:security/lxqt-sudo-l10n \
	lxqt-libfm-l10n>=0.11:x11/lxqt-libfm-l10n \
	lxqt-pcmanfm-l10n>=0.11:x11-fm/lxqt-pcmanfm-l10n \
	lxqt-config-l10n>=0.11:sysutils/lxqt-config-l10n \
	lxqt-policykit-l10n>=0.11:sysutils/lxqt-policykit-l10n \
	lxqt-about-l10n>=0.11:x11/lxqt-about-l10n \
	lxqt-globalkeys-l10n>=0.11:x11/lxqt-globalkeys-l10n \
	lxqt-runner-l10n>=0.11:x11/lxqt-runner-l10n \
	lxqt-pavucontrol-l10n>=0.11:audio/lxqt-pavucontrol-l10n \
	lxqt-obconf-l10n>=0.11:x11-wm/lxqt-obconf-l10n \
	lxqt-panel-l10n>=0.11:x11-wm/lxqt-panel-l10n \
	lxqt-session-l10n>=0.11:x11-wm/lxqt-session-l10n \
	lxqt-admin-l10n>=0.11:sysutils/lxqt-admin-l10n

USES=	lxqt metaport tar:xz
USE_LXQT=	lxqt

.include <bsd.port.mk>
