# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-l10n
PORTVERSION=	0.11.1
CATEGORIES=	x11

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Translations of LXQt components

LICENSE=	LGPL21+

RUN_DEPENDS=	liblxqt-l10n>=0.11:devel/liblxqt-l10n \
	lxqt-notificationd-l10n>=0.11:deskutils/lxqt-notificationd-l10n \
	lximageqt-l10n>=0.11:graphics/lximageqt-l10n \
	lxqt-openssh-l10n>=0.11:security/lxqt-openssh-l10n \
	lxqt-sudo-l10n>=0.11:security/lxqt-sudo-l10n \
	libfmqt-l10n>=0.11:x11/libfmqt-l10n \
	pcmanfmqt-l10n>=0.11:x11-fm/pcmanfmqt-l10n \
	lxqt-config-l10n>=0.11:sysutils/lxqt-config-l10n \
	lxqt-policykit-l10n>=0.11:sysutils/lxqt-policykit-l10n \
	lxqt-about-l10n>=0.11:x11/lxqt-about-l10n \
	lxqt-globalkeys-l10n>=0.11:x11/lxqt-globalkeys-l10n \
	lxqt-runner-l10n>=0.11:x11/lxqt-runner-l10n \
	pavucontrolqt-l10n>=0.11:audio/pavucontrolqt-l10n \
	obconfqt-l10n>=0.11:x11-wm/obconfqt-l10n \
	lxqt-panel-l10n>=0.11:x11-wm/lxqt-panel-l10n \
	lxqt-session-l10n>=0.11:x11-wm/lxqt-session-l10n \
	lxqt-admin-l10n>=0.11:sysutils/lxqt-admin-l10n

USES= metaport

.include <bsd.port.mk>
