# Created by: Kris Moore <kmoore@FreeBSD.org>
# $FreeBSD$

PORTNAME=	lxmenu-data
PORTVERSION=	0.1.4
CATEGORIES=	x11
MASTER_SITES=	SF/lxde/${PORTNAME}%20%28desktop%20menu%29/${PORTNAME}%20${PORTVERSION}/

MAINTAINER=	horia@racoviceanu.com
COMMENT=	Freedesktop.org application menu definition files

LICENSE=	LGPL21

USES=		gmake gettext tar:xz
USE_GNOME=	intltool
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
