# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-globalkeys
PORTVERSION=	0.9.0
CATEGORIES=	x11
MASTER_SITES=	LXQT

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Global keyboard shortcuts registration

USES=	cmake pkgconfig gettext lxqt tar:xz
USE_QT5=	dbus linguisttools widgets
USE_LXQT=	lxqt
USE_XORG=	x11

.include <bsd.port.mk>
