# Created by: Jesper Schmitz Mouridsen
# $FreeBSD$

PORTNAME=	lxqt-themes
PORTVERSION=	0.12.0
CATEGORIES=	x11-themes
MASTER_SITES=	LXQT

MAINTAINER=	jesper@schmitz.computer
COMMENT=	Themes for the LXQt desktop

LICENSE=	LGPL21+

USES=		lxqt cmake:outsource tar:xz

.include <bsd.port.mk>
