# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-openssh-askpass
PORTVERSION=	0.10.0
CATEGORIES=	security
MASTER_SITES=	LXQT

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	LXQT GUI dialog for OpenSSH authentication

USES=	cmake:outsource gettext lxqt pkgconfig tar:xz
USE_QT5=	buildtools_build qmake_build linguisttools widgets
USE_LXQT=	lxqt

.include <bsd.port.mk>
