# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-notificationd
PORTVERSION=	0.9.0
CATEGORIES=	deskutils
MASTER_SITES=	LXQT

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	LXQt notification daemon

USES=	cmake pkgconfig gettext lxqt tar:xz
USE_QT5=	dbus linguisttools widgets
USE_LXQT=	lxqt

.include <bsd.port.mk>
