# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-notificationd
PORTVERSION=	0.9.0
CATEGORIES=	deskutils
MASTER_SITES=	http://downloads.lxqt.org/%SUBDIR%/
DIST_SUBDIR=	lxqt

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	LXQt notification daemon

LICENSE=	LGPL21

USES=	cmake pkgconfig gettext tar:xz
USE_QT5=	dbus linguisttools widgets
USE_LXQT=	lxqt

.include <bsd.port.mk>
