# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-notificationd
PORTVERSION=	0.10.0
CATEGORIES=	deskutils
MASTER_SITES=	LXQT

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	LXQt notification daemon

USES=	cmake:outsource gettext kde:5 lxqt pkgconfig tar:xz
USE_QT5=	dbus linguisttools widgets
USE_KDE=	windowsystem
USE_LXQT=	lxqt

.include <bsd.port.mk>
