# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-about
PORTVERSION=	0.9.0
CATEGORIES=	x11
MASTER_SITES=	http://downloads.lxqt.org/%SUBDIR%/
DIST_SUBDIR=	lxqt

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	About dialog of LXQt

LICENSE=	LGPL21

USES=	cmake pkgconfig gettext tar:xz
USE_QT5=	dbus widgets x11extras
USE_LXQT=	lxqt

.include <bsd.port.mk>
