# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	lxqt-about
PORTVERSION=	0.10.0
CATEGORIES=	x11
MASTER_SITES=	LXQT
DIST_SUBDIR=	lxqt

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	About dialog of LXQt

LICENSE=	LGPL21

USES=	cmake:outsource gettext lxqt pkgconfig tar:xz
USE_QT5=	buildtools_build qmake_build widgets x11extras
USE_LXQT=	lxqt

.include <bsd.port.mk>
