# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	pcmanfm-qt
PORTVERSION=	0.9.0
CATEGORIES=	x11-fm
MASTER_SITES=	http://downloads.lxqt.org/%SUBDIR%/
DIST_SUBDIR=	lxqt

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	LXQt file manager

LICENSE=	GPLv2

USES=	cmake pkgconfig gettext desktop-file-utils tar:xz
USE_GNOME=	glib20
USE_QT5=	dbus linguisttools widgets x11extras
USE_LXQT=	libfm

.include <bsd.port.mk>
