# Created by: Olivier Duchateau
# $FreeBSD$

PORTNAME=	libqtxdg
PORTVERSION=	1.3.0
CATEGORIES=	devel
MASTER_SITES=	LXQT/${PORTNAME}/${PORTVERSION}

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Qt implementation of freedesktop.org xdg specs


USES=	cmake:outsource lxqt pkgconfig tar:xz
USE_QT5=	core dbus widgets xml

.include <bsd.port.mk>
